---
inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rspec

AllCops:
  DisabledByDefault: true

  DisplayCopNames: true
  DisplayStyleGuide: true

  TargetRubyVersion: 3.1

RSpec:
  Enabled: true
